openapi: 3.0.3
info:
  title: AI Todo Chatbot API
  description: API for interacting with the AI-powered todo chatbot
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/{user_id}/chat:
    post:
      summary: Process natural language input and return AI response
      description: |
        Main chat endpoint that accepts natural language input and processes it
        through the AI agent which may invoke MCP tools to manage tasks.
      parameters:
        - name: user_id
          in: path
          required: true
          description: The authenticated user's ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: The user's natural language message
                  example: "Add buy groceries to my list"
      responses:
        '200':
          description: Successful response from the AI chatbot
          content:
            application/json:
              schema:
              type: object
              properties:
                response:
                  type: string
                  description: The AI's response to the user
                  example: "I've added 'buy groceries' to your task list."
                tool_invocations:
                  type: array
                  items:
                    type: object
                    properties:
                      tool_name:
                        type: string
                        description: Name of the tool that was invoked
                      parameters:
                        type: object
                        description: Parameters passed to the tool
                      result:
                        type: object
                        description: Result from the tool invocation
                conversation_id:
                  type: string
                  description: ID of the conversation for continuity
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - user attempting to access another user's data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/{user_id}/tasks:
    get:
      summary: List all tasks for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The authenticated user's ID
          schema:
            type: string
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The authenticated user's ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: Title of the task
                description:
                  type: string
                  description: Optional description of the task
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  task:
                    $ref: '#/components/schemas/Task'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        title:
          type: string
          description: Task title
        description:
          type: string
          description: Task description (optional)
        completed:
          type: boolean
          description: Whether the task is completed
        user_id:
          type: string
          description: ID of the user who owns the task
        created_at:
          type: string
          format: date-time
          description: When the task was created
        updated_at:
          type: string
          format: date-time
          description: When the task was last updated
        completed_at:
          type: string
          format: date-time
          description: When the task was completed (if completed)
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at

    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the message
        conversation_id:
          type: string
          format: uuid
          description: ID of the conversation this message belongs to
        role:
          type: string
          enum: [user, assistant]
          description: Who sent the message
        content:
          type: string
          description: The message content
        timestamp:
          type: string
          format: date-time
          description: When the message was sent
        tool_calls:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the tool called
              arguments:
                type: object
                description: Arguments passed to the tool
        tool_responses:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the tool that responded
              result:
                type: object
                description: Result from the tool
      required:
        - id
        - conversation_id
        - role
        - content
        - timestamp

    Conversation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the conversation
        user_id:
          type: string
          description: ID of the user who owns the conversation
        title:
          type: string
          description: Auto-generated or user-defined conversation title
        created_at:
          type: string
          format: date-time
          description: When the conversation was started
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
      required:
        - id
        - user_id
        - created_at
        - updated_at

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
      required:
        - error
        - code